# Generated by Django 5.1.2 on 2024-10-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Momo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('buff', 'buff'), ('chicken', 'chicken'), ('veg', 'veg')], max_length=200)),
                ('image', models.ImageField(upload_to='images')),
                ('price', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
        ),
    ]
