# Generated by Django 5.1.2 on 2024-11-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_momo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
